<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\sign.snk</AssemblyOriginatorKeyFile>
    <PublicSign>true</PublicSign>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Tmds2.DBus/Tmds2.DBus.csproj" />
    <ProjectReference Include="../../src/Tmds2.DBus.Protocol/Tmds2.DBus.Protocol.csproj">
      <Aliases>Protocol</Aliases>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <Content Include="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
